#!/bin/bash

cd lib/libfdr/
make clean
make all
cd ..
cd libllist/
make clean
make all
cd ..
cd libgraph/
make clean
make all
cd ..
cd libabs/
make clean
make all
cd ..
cd bt\-5.0.0
make clean
make all
